### PR TITLE
Added a paging in the demo and added a provider for fake data

### PR DESCRIPTION
**Pull request by Nordes**
Since I wanted to use this template for some code demo, I wanted to add some paging and some basic dependency injection (1 data provider in this case).

You can reject the pull request if you prefer to keep the template as basic as it can be.

**Changes:**
- Added paging within the fake-data page.
- Refactored C# to move some code within a provider
- Added in the startup 1 dependency injection 
- Renamed the controller to WeatherController (make more sense) and the route is now /weather/forecasts with 2 query string (From, to). The code is not perfect but for demo purpose I think it's quite ok.

Look:
image

### CODE REVIEW

**Comment by MarkPieszak** [comment]
@Nordes this looks so awesome!! Great job 👍🎖🎖🎖

It looks like there are some branch conflicts? Can you get latest from remote master, and pull them in - I'll get it merged as soon as it's all fixed up!

You rock 🚀

**Comment by Nordes** [comment]
I'll do the pull tonight from home ;).

**Comment by Nordes** [comment]
Normally all is good. You can do a validation and then accept the PR. Sorry if I make a lot of commit ;) I tend to prefer to have multiple small commit on specific things.

**Comment by MarkPieszak** [comment]
Great! Merging now 👍

**Pull request merged**
