### PR TITLE
Fix publish and add missing dependencies

### PR DESCRIPTION
**Pull request by Nordes**
Hi, 

Here's what's included
- Fix the publish to build only once the vendor instead of 2 times.
- Fixed the build/publish to be aligned regarding the environment. 
  - Now we use the NODE_ENV process variable. It's injected (see csproj/package.json)
  - Webpack does not use the `env` variable anymore and we also output what version we're producing (`development` or `production`).
- Aligned the readme in the template itself to be the same as the root folder.
  - Fixed the in-page linking with the ToC.
- Ajusted the license to be until 2016-2018
- Lint-ing fixed. I added the missing libraries as dev-dependencies. Now you have full recognition within visual studio code if you don't have all the linting applied globally.
  - Fixed the spacing to be 2 (since standard was used). I used the `eslint ... --fix` to fix all.

Note: I would prefer to push only one commit, but I am not too confident in my rebasing skills ;).

### CODE REVIEW

**Comment by Nordes** [comment]
Added the fix regarding the issue #79 . 

Also I found out while publishing that the font-awesome were not being shaken. So I changed the way the import of icons was done. Now we have only the selected icons within the publish and nothing more.

**Comment by MarkPieszak** [comment]
I just merged in #80, it looks like it gave some minor conflicts here did you want to take a look and we can get this awesome PR in as well? :+1: 💯

**Comment by Nordes** [comment]
Sorry for the delay ;). I will look tonight. (Japan time)

**Comment by Nordes** [comment]
Update completed, please validate and then enjoy ;).

**Comment by MarkPieszak** [comment]
This is great! Merged it :100: :100:

**Pull request merged**
